project:
  type: website

website:
  title: "Population genomics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: 0_introduction_to__linux.qmd
        text: Linux
      - href: 1_qc_and_read_mapping.qmd
        text: qc, read mapping
      - href: 2_vcf_manipulation.qmd
        text: vcf manipulation
      - about.qmd

format:
  html:
    theme: united
    self-contained: true
    page-layout: full
    css: styles.css
    toc: true
    number-sections: true



