project:
  type: website

website:
  title: "Population genomics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: content/0_introduction_to_linux.qmd
        text: Linux
      - href: content/1_qc_and_read_mapping.qmd
        text: qc, read mapping
      - href: content/2_vcf_manipulation.qmd
        text: vcf manipulation

format:
  html:
    theme:
      light: flatly
      dark: darkly
    self-contained: true
    page-layout: full
    css: styles.css
    toc: true
    number-sections: true

execute:
  freeze: auto




